image: alpine:latest

stages:
  - deploy

pages:
  stage: deploy
  script:
    - mkdir public
    - cp index.html app.mjs styles.css favicon.png kai-quartz.csv kuro-quartz.csv kuro2-quartz.csv public/
    - cp -R src public/
  artifacts:
    paths:
      - public
    expire_in: never
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
